'''import pymysql'''

'''try:
    db=pymysql.connect(host='localhost',user='root',pasword='',database='topsdata)
    print('database connected')
except exception as a :
    print(e)'''

'''cr=db.cursor()'''

'''#create table
create_tbl="create table studinfo(id integer primary key auto_increment,name varchar(20),city varchar(20))"'''

'''try:
    cr.execute(create_tbl)
    print("table created!")
except exception as e:
    print(e)'''

